# Generated by Django 4.2.5 on 2023-11-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='token_otp',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
