# Generated by Django 4.2.5 on 2023-11-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_appuser_email_verified_appuser_token_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='token_otp',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
