# Generated by Django 4.2.6 on 2023-11-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_appuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Freelancer', 'FREELANCER'), ('Full Time', 'FULL TIME'), ('Part Time', 'PART TIME'), ('Contract', 'CONTRACT'), ('Seasonal Worker', 'SEASONAL WORKER'), ('Self-employed', 'SELF-EMPLOYED')], max_length=50, null=True),
        ),
    ]
