# Generated by Django 4.2.6 on 2023-12-28 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("countries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("bio", models.TextField()),
                ("about", models.TextField()),
                ("target_audience", models.TextField()),
                (
                    "logo",
                    models.ImageField(
                        default="payment-gateway.png/", upload_to="payment_gateway/"
                    ),
                ),
                ("rate_sum", models.IntegerField(blank=True, default=0)),
                ("total_ratings", models.IntegerField(blank=True, default=0)),
                ("average_rating", models.IntegerField(blank=True, default=0)),
                ("countries", models.ManyToManyField(to="countries.country")),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        default="payment-option.png/", upload_to="payment_option/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                (
                    "payment_gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paymentoptions.paymentgateway",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="payment_options",
            field=models.ManyToManyField(to="paymentoptions.paymentmethod"),
        ),
    ]
