# Generated by Django 4.2.5 on 2023-10-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoption',
            name='payment_option',
            field=models.CharField(default='No Payment Options Available', max_length=255),
        ),
    ]
