# Generated by Django 4.2.6 on 2023-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paymentoptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgateway",
            name="accepted_methods",
            field=models.TextField(blank=True, null=True),
        ),
    ]
