# Generated by Django 4.2.6 on 2023-12-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentoptions', '0002_paymentgateway_accepted_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
