# Generated by Django 4.2.5 on 2023-10-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentoptions', '0002_alter_paymentoption_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoption',
            name='payment_option',
            field=models.CharField(max_length=255),
        ),
    ]
