# Generated by Django 4.2.6 on 2023-12-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentoptions', '0004_alter_userrating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='accepted_methods',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
